import { createContext, useContext, useState } from "react";

export const LANGS = [
  { code:"en", label:"English",    flag:"EN"  },
  { code:"ta", label:"தமிழ்",      flag:"த"   },
  { code:"hi", label:"हिंदी",      flag:"हि"  },
  { code:"te", label:"తెలుగు",     flag:"తె"  },
  { code:"kn", label:"ಕನ್ನಡ",     flag:"ಕ"   },
  { code:"ml", label:"മലയാളം",    flag:"മ"   },
  { code:"bn", label:"বাংলা",      flag:"ব"   },
  { code:"mr", label:"मराठी",      flag:"म"   },
  { code:"gu", label:"ગુજરાતી",    flag:"ગ"   },
];

export const HERBS = {
  en: { Basil:"Basil",    Mint:"Mint",     Rosemary:"Rosemary", Thyme:"Thyme",     Coriander:"Coriander", Lettuce:"Lettuce",    Spinach:"Spinach",    Chives:"Chives",  Parsley:"Parsley"   },
  ta: { Basil:"துளசி",    Mint:"புதினா",   Rosemary:"ரோஸ்மேரி", Thyme:"தைம்",     Coriander:"கொத்தமல்லி",Lettuce:"கீரை",      Spinach:"பசலை கீரை", Chives:"சைவ்ஸ்",  Parsley:"பார்ஸ்லி"  },
  hi: { Basil:"तुलसी",    Mint:"पुदीना",   Rosemary:"रोज़मेरी",  Thyme:"थाइम",    Coriander:"धनिया",     Lettuce:"सलाद पत्ता",Spinach:"पालक",      Chives:"चाइव्स",  Parsley:"अजमोद"     },
  te: { Basil:"తులసి",    Mint:"పుదీనా",   Rosemary:"రోజ్‌మేరీ", Thyme:"థైమ్",    Coriander:"ధనియాలు",  Lettuce:"లెట్యూస్",  Spinach:"పాలకూర",    Chives:"చైవ్స్",  Parsley:"పార్స్లీ"  },
  kn: { Basil:"ತುಳಸಿ",    Mint:"ಪುದೀನ",   Rosemary:"ರೋಸ್‌ಮೆರಿ", Thyme:"ಥೈಮ್",    Coriander:"ಕೊತ್ತಂಬರಿ",Lettuce:"ಲೆಟ್ಟೂಸ್",  Spinach:"ಪಾಲಕ",      Chives:"ಚೈವ್ಸ್",  Parsley:"ಪಾರ್ಸ್ಲಿ" },
  ml: { Basil:"തുളസി",    Mint:"പുതിന",    Rosemary:"റോസ്‌മേരി", Thyme:"തൈം",     Coriander:"മല്ലി",     Lettuce:"ലെറ്റ്യൂസ്",Spinach:"ചീര",       Chives:"ചൈവ്സ്",  Parsley:"പാഴ്‌സ്ലി" },
  bn: { Basil:"তুলসি",    Mint:"পুদিনা",   Rosemary:"রোজমেরি",   Thyme:"থাইম",    Coriander:"ধনিয়া",    Lettuce:"লেটুস",     Spinach:"পালং শাক",  Chives:"চাইভস",   Parsley:"পার্সলে"   },
  mr: { Basil:"तुळस",     Mint:"पुदिना",   Rosemary:"रोझमेरी",   Thyme:"थाईम",    Coriander:"कोथिंबीर",  Lettuce:"लेट्यूस",   Spinach:"पालक",      Chives:"चाइव्स",  Parsley:"अजमोदा"    },
  gu: { Basil:"તુલસી",    Mint:"ફુદીનો",   Rosemary:"રોઝમેરી",   Thyme:"થાઇમ",    Coriander:"ધાણા",      Lettuce:"લેટ્યુસ",   Spinach:"પાલક",      Chives:"ચાઇવ્ઝ",  Parsley:"અજમો"      },
};

export const T = {
  en: {
    /* SimpleView */
    simpleMode:"Simple Mode", farmerTab:"🌱 Farmer", chefTab:"👨‍🍳 Chef",
    backFull:"← Full Dashboard", iconMode:"Icons Only", labelMode:"Labels",
    sensors:"Farm Sensors", harvest:"Harvest Readiness", available:"Available Today",
    temp:"Temperature", humidity:"Moisture", air:"Air Quality", light:"Light", ph:"pH",
    good:"GOOD ✅", warn:"CHECK ⚠️", bad:"URGENT 🚨",
    fresh:"Very Fresh", pickSoon:"Pick within 2 days", pickNow:"Pick NOW!",
    daysLeft:"days left", kgAvail:"kg stock", priceKg:"per kg",
    orderSoon:"Order Soon", plenty:"In Stock", lowStock:"Low!",
    whatsapp:"📱 Order via WhatsApp", expiresIn:"Expires in",
    harvestPrediction:"Best Harvest Day",
    /* Navigation */
    nav_dashboard:"Dashboard", nav_analytics:"Analytics",
    nav_freshness:"Freshness Tracker", nav_market:"Herb Market",
    nav_waste:"Waste Predictor", nav_pulse:"Chef Connect",
    nav_advisor:"AI Advisor", nav_simple:"Simple Mode",
    sec_overview:"OVERVIEW", sec_ai:"AI FEATURES", sec_engage:"ENGAGEMENT",
    /* Common UI */
    lbl_refresh:"Refresh", lbl_signout:"Sign out",
    lbl_send_email:"Send via Email", lbl_submit:"Submit",
    lbl_clear_chat:"Clear chat", lbl_active_alerts:"Active Alerts",
    lbl_sort_by:"Sort by:", lbl_alerts:"alerts",
    lbl_name:"Your name", lbl_email:"Your email",
    lbl_rating:"Rating", lbl_reviews:"Chef Reviews",
    lbl_add_herb:"+ Add herb", lbl_send_order:"Send Order via WhatsApp",
    lbl_place_order:"Place Order",
    /* Page titles & subtitles */
    pg_fresh_title:"Freshness Tracker", pg_fresh_sub:"AI-powered shelf-life prediction · live batch monitoring",
    pg_market_title:"Herb Stock Market", pg_market_sub:"Live herb prices · refreshes every 60s",
    pg_waste_title:"Waste Predictor", pg_waste_sub:"Flash sale builder — turn excess into revenue",
    pg_pulse_title:"Chef Connect", pg_pulse_sub:"Your feedback reaches the farm directly · shapes every harvest",
    pg_advisor_title:"AI Advisor", pg_advisor_sub:"Groq Llama 70B + Mistral Small · Context-injected farm intelligence",
    /* Dashboard */
    lbl_yield:"Total Yield", lbl_water:"Water Usage", lbl_power:"Power",
    lbl_delivery:"Avg Delivery", lbl_live_sensors:"Live Sensors",
    lbl_farm_health:"Farm Health Score",
    pg_dash_title:"Farm Dashboard", pg_dash_sub:"AgriIntel · Real-time farm intelligence",
    /* Analytics */
    pg_analytics_sub:"Detailed farm performance · interactive filters",
    /* Photo Inspect */
    pg_photo_title:"AI Photo Inspection", pg_photo_sub:"Upload herb photo → AI detects quality, wilt & damage",
    lbl_which_herb:"Which herb are you inspecting?", lbl_inspect_btn:"Inspect Herb Quality", lbl_inspect_another:"Inspect Another Photo",
    /* Freshness */
    lbl_avg_freshness:"Avg Freshness", lbl_active_batches:"Active Batches", lbl_wilt_alerts:"Wilt Alerts",
    lbl_climate_sim:"Climate Simulator", lbl_qr_btn:"Generate Batch QR",
    /* Chef Connect */
    lbl_your_identity:"Your Identity", lbl_overall_rating_lbl:"Overall Rating",
    herbs: HERBS.en,
  },

  ta: {
    simpleMode:"எளிய பயன்பாடு", farmerTab:"🌱 விவசாயி", chefTab:"👨‍🍳 சமையல்காரர்",
    backFull:"← முழு டாஷ்போர்டு", iconMode:"படங்கள் மட்டும்", labelMode:"பெயர்களுடன்",
    sensors:"பண்ணை உணர்விகள்", harvest:"அறுவடை நிலை", available:"இன்று கிடைக்கும்",
    temp:"வெப்பநிலை", humidity:"ஈரப்பதம்", air:"காற்று தரம்", light:"ஒளி", ph:"pH அளவு",
    good:"நல்லது ✅", warn:"கவனி ⚠️", bad:"அவசரம் 🚨",
    fresh:"மிகவும் புதியது", pickSoon:"2 நாளில் பறிக்கவும்", pickNow:"இப்போதே பறிக்கவும்!",
    daysLeft:"நாட்கள் மீதம்", kgAvail:"கிலோ உள்ளது", priceKg:"கிலோவுக்கு",
    orderSoon:"விரைவில் ஆர்டர்", plenty:"கையிருப்பு உள்ளது", lowStock:"குறைவாக உள்ளது!",
    whatsapp:"📱 WhatsApp ஆர்டர்", expiresIn:"காலாவதியாகும் நேரம்",
    harvestPrediction:"சிறந்த அறுவடை நாள்",
    nav_dashboard:"டாஷ்போர்டு", nav_analytics:"பகுப்பாய்வு",
    nav_freshness:"புதுமை கண்காணிப்பு", nav_market:"மூலிகை சந்தை",
    nav_waste:"கழிவு கணிப்பு", nav_pulse:"சமையல்காரர் இணைப்பு",
    nav_advisor:"AI ஆலோசகர்", nav_simple:"எளிய பயன்பாடு",
    sec_overview:"கண்ணோட்டம்", sec_ai:"AI அம்சங்கள்", sec_engage:"ஈடுபாடு",
    lbl_refresh:"புதுப்பி", lbl_signout:"வெளியேறு",
    lbl_send_email:"மின்னஞ்சல் அனுப்பு", lbl_submit:"சமர்ப்பி",
    lbl_clear_chat:"அரட்டை அழி", lbl_active_alerts:"செயலில் உள்ள எச்சரிக்கைகள்",
    lbl_sort_by:"வரிசை:", lbl_alerts:"எச்சரிக்கைகள்",
    lbl_name:"உங்கள் பெயர்", lbl_email:"உங்கள் மின்னஞ்சல்",
    lbl_rating:"மதிப்பீடு", lbl_reviews:"சமையல்காரர் கருத்துகள்",
    lbl_add_herb:"+ மூலிகை சேர்", lbl_send_order:"WhatsApp மூலம் ஆர்டர் அனுப்பு",
    lbl_place_order:"ஆர்டர் செய்",
    pg_fresh_title:"புதுமை கண்காணிப்பு", pg_fresh_sub:"AI-இயங்கும் புதுமை கணிப்பு",
    pg_market_title:"மூலிகை சந்தை", pg_market_sub:"நேரடி மூலிகை விலைகள்",
    pg_waste_title:"கழிவு கணிப்பு", pg_waste_sub:"கழிவை வருமானமாக மாற்றுங்கள்",
    pg_pulse_title:"சமையல்காரர் கருத்து", pg_pulse_sub:"உங்கள் அனுபவத்தை பகிரவும்",
    pg_advisor_title:"AI ஆலோசகர்", pg_advisor_sub:"Groq Llama 70B · பண்ணை தகவல்களுடன் இயங்கும்",
    lbl_yield:"மொத்த விளைச்சல்", lbl_water:"தண்ணீர் பயன்பாடு", lbl_power:"மின்சாரம்",
    lbl_delivery:"சராசரி விநியோகம்", lbl_live_sensors:"நேரடி உணர்விகள்",
    lbl_farm_health:"பண்ணை ஆரோக்கிய மதிப்பெண்",
    pg_dash_title:"பண்ணை டாஷ்போர்டு", pg_dash_sub:"AgriIntel · நேரடி பண்ணை தகவல்",
    pg_analytics_sub:"விரிவான பண்ணை செயல்திறன் · வடிகட்டிகள்",
    pg_photo_title:"AI புகைப்பட ஆய்வு", pg_photo_sub:"மூலிகை புகைப்படம் → AI தரம் கண்டறியும்",
    lbl_which_herb:"எந்த மூலிகையை ஆய்வு செய்கிறீர்கள்?", lbl_inspect_btn:"மூலிகை தரம் ஆய்வு செய்", lbl_inspect_another:"மற்றொரு புகைப்படம் ஆய்வு",
    lbl_avg_freshness:"சராசரி புதுமை", lbl_active_batches:"செயலில் தொகுப்புகள்", lbl_wilt_alerts:"வாடல் எச்சரிக்கைகள்",
    lbl_climate_sim:"காலநிலை உருவகம்", lbl_qr_btn:"QR குறியீடு உருவாக்கு",
    lbl_your_identity:"உங்கள் அடையாளம்", lbl_overall_rating_lbl:"ஒட்டுமொத்த மதிப்பீடு",
    herbs: HERBS.ta,
  },

  hi: {
    simpleMode:"सरल मोड", farmerTab:"🌱 किसान", chefTab:"👨‍🍳 रसोइया",
    backFull:"← पूरा डैशबोर्ड", iconMode:"केवल आइकन", labelMode:"लेबल के साथ",
    sensors:"खेत सेंसर", harvest:"फसल की स्थिति", available:"आज उपलब्ध",
    temp:"तापमान", humidity:"नमी", air:"हवा की गुणवत्ता", light:"रोशनी", ph:"pH स्तर",
    good:"अच्छा ✅", warn:"ध्यान दें ⚠️", bad:"तुरंत करें 🚨",
    fresh:"बहुत ताज़ा", pickSoon:"2 दिन में तोड़ें", pickNow:"अभी तोड़ें!",
    daysLeft:"दिन बचे", kgAvail:"किलो उपलब्ध", priceKg:"प्रति किलो",
    orderSoon:"जल्दी ऑर्डर करें", plenty:"पर्याप्त है", lowStock:"कम स्टॉक!",
    whatsapp:"📱 WhatsApp ऑर्डर", expiresIn:"समाप्त होने में",
    harvestPrediction:"सबसे अच्छा कटाई का दिन",
    nav_dashboard:"डैशबोर्ड", nav_analytics:"विश्लेषण",
    nav_freshness:"ताज़गी ट्रैकर", nav_market:"जड़ी-बूटी बाज़ार",
    nav_waste:"अपव्यय भविष्यवक्ता", nav_pulse:"शेफ कनेक्ट",
    nav_advisor:"AI सलाहकार", nav_simple:"सरल मोड",
    sec_overview:"अवलोकन", sec_ai:"AI सुविधाएँ", sec_engage:"सहभागिता",
    lbl_refresh:"ताज़ा करें", lbl_signout:"साइन आउट",
    lbl_send_email:"ईमेल भेजें", lbl_submit:"जमा करें",
    lbl_clear_chat:"चैट साफ़ करें", lbl_active_alerts:"सक्रिय अलर्ट",
    lbl_sort_by:"क्रम:", lbl_alerts:"अलर्ट",
    lbl_name:"आपका नाम", lbl_email:"आपका ईमेल",
    lbl_rating:"रेटिंग", lbl_reviews:"शेफ समीक्षाएँ",
    lbl_add_herb:"+ जड़ी-बूटी जोड़ें", lbl_send_order:"WhatsApp से ऑर्डर भेजें",
    lbl_place_order:"ऑर्डर करें",
    pg_fresh_title:"ताज़गी ट्रैकर", pg_fresh_sub:"AI-संचालित शेल्फ लाइफ पूर्वानुमान",
    pg_market_title:"जड़ी-बूटी बाज़ार", pg_market_sub:"लाइव जड़ी-बूटी कीमतें",
    pg_waste_title:"अपव्यय भविष्यवक्ता", pg_waste_sub:"अपव्यय को आय में बदलें",
    pg_pulse_title:"शेफ पल्स", pg_pulse_sub:"अपना अनुभव साझा करें",
    pg_advisor_title:"AI सलाहकार", pg_advisor_sub:"Groq Llama 70B · लाइव फार्म डेटा के साथ",
    lbl_yield:"कुल उपज", lbl_water:"पानी का उपयोग", lbl_power:"बिजली",
    lbl_delivery:"औसत डिलीवरी", lbl_live_sensors:"लाइव सेंसर",
    lbl_farm_health:"फार्म स्वास्थ्य स्कोर",
    pg_dash_title:"फार्म डैशबोर्ड", pg_dash_sub:"AgriIntel · रियल-टाइम फार्म इंटेलिजेंस",
    pg_analytics_sub:"विस्तृत फार्म प्रदर्शन · इंटरैक्टिव फ़िल्टर",
    pg_photo_title:"AI फोटो निरीक्षण", pg_photo_sub:"जड़ी-बूटी फोटो → AI गुणवत्ता जांच",
    lbl_which_herb:"आप कौन सी जड़ी-बूटी जाँच रहे हैं?", lbl_inspect_btn:"जड़ी-बूटी गुणवत्ता जाँचें", lbl_inspect_another:"दूसरी फ़ोटो जाँचें",
    lbl_avg_freshness:"औसत ताज़गी", lbl_active_batches:"सक्रिय बैच", lbl_wilt_alerts:"मुरझाने की चेतावनी",
    lbl_climate_sim:"जलवायु सिमुलेटर", lbl_qr_btn:"बैच QR बनाएं",
    lbl_your_identity:"आपकी पहचान", lbl_overall_rating_lbl:"समग्र रेटिंग",
    herbs: HERBS.hi,
  },

  te: {
    simpleMode:"సరళ మోడ్", farmerTab:"🌱 రైతు", chefTab:"👨‍🍳 వంట మాస్టర్",
    backFull:"← పూర్తి డ్యాష్‌బోర్డ్", iconMode:"చిహ్నాలు మాత్రమే", labelMode:"లేబుళ్లతో",
    sensors:"వ్యవసాయ సెన్సార్లు", harvest:"పంట స్థితి", available:"నేడు అందుబాటులో",
    temp:"ఉష్ణోగ్రత", humidity:"తేమ", air:"గాలి నాణ్యత", light:"వెలుతురు", ph:"pH స్థాయి",
    good:"మంచిది ✅", warn:"జాగ్రత్త ⚠️", bad:"అర్జెంట్ 🚨",
    fresh:"చాలా తాజా", pickSoon:"2 రోజుల్లో కోయండి", pickNow:"ఇప్పుడే కోయండి!",
    daysLeft:"రోజులు మిగిలాయి", kgAvail:"కిలో అందుబాటులో", priceKg:"కిలోకు",
    orderSoon:"త్వరగా ఆర్డర్ చేయండి", plenty:"స్టాక్ ఉంది", lowStock:"తక్కువ స్టాక్!",
    whatsapp:"📱 WhatsApp ఆర్డర్", expiresIn:"గడువు ముగిసే వరకు",
    harvestPrediction:"ఉత్తమ పంట రోజు",
    nav_dashboard:"డాష్‌బోర్డ్", nav_analytics:"విశ్లేషణలు",
    nav_freshness:"తాజాదనం ట్రాకర్", nav_market:"ఔషధ మొక్కల మార్కెట్",
    nav_waste:"వ్యర్థ అంచనా", nav_pulse:"చెఫ్ కనెక్ట్",
    nav_advisor:"AI సలహాదారు", nav_simple:"సరళ మోడ్",
    sec_overview:"అవలోకనం", sec_ai:"AI ఫీచర్లు", sec_engage:"నిమగ్నత",
    lbl_refresh:"రిఫ్రెష్", lbl_signout:"సైన్ అవుట్",
    lbl_send_email:"ఈమెయిల్ పంపు", lbl_submit:"సమర్పించు",
    lbl_clear_chat:"చాట్ క్లియర్", lbl_active_alerts:"సక్రియ హెచ్చరికలు",
    lbl_sort_by:"క్రమం:", lbl_alerts:"హెచ్చరికలు",
    lbl_name:"మీ పేరు", lbl_email:"మీ ఈమెయిల్",
    lbl_rating:"రేటింగ్", lbl_reviews:"చెఫ్ సమీక్షలు",
    lbl_add_herb:"+ మొక్క జోడించు", lbl_send_order:"WhatsApp ద్వారా ఆర్డర్",
    lbl_place_order:"ఆర్డర్ చేయి",
    pg_fresh_title:"తాజాదనం ట్రాకర్", pg_fresh_sub:"AI-ఆధారిత షెల్ఫ్ లైఫ్ అంచనా",
    pg_market_title:"ఔషధ మొక్కల మార్కెట్", pg_market_sub:"నేరుగా ఔషధ మొక్కల ధరలు",
    pg_waste_title:"వ్యర్థ అంచనా", pg_waste_sub:"వ్యర్థాన్ని ఆదాయంగా మార్చండి",
    pg_pulse_title:"చెఫ్ పల్స్", pg_pulse_sub:"మీ అనుభవాన్ని పంచుకోండి",
    pg_advisor_title:"AI సలహాదారు", pg_advisor_sub:"Groq Llama 70B · నేరుగా ఫార్మ్ డేటాతో",
    lbl_yield:"మొత్తం దిగుబడి", lbl_water:"నీటి వినియోగం", lbl_power:"విద్యుత్",
    lbl_delivery:"సగటు డెలివరీ", lbl_live_sensors:"నేరుగా సెన్సార్లు",
    lbl_farm_health:"ఫార్మ్ ఆరోగ్య స్కోర్",
    pg_dash_title:"ఫార్మ్ డాష్‌బోర్డ్", pg_dash_sub:"AgriIntel · నేరుగా ఫార్మ్ తెలివిడి",
    pg_analytics_sub:"వివరణాత్మక ఫార్మ్ పనితీరు · ఇంటరాక్టివ్ ఫిల్టర్లు",
    pg_photo_title:"AI ఫోటో తనిఖీ", pg_photo_sub:"ఔషధ మొక్క ఫోటో → AI నాణ్యత పరీక్ష",
    lbl_which_herb:"మీరు ఏ మొక్కను తనిఖీ చేస్తున్నారు?", lbl_inspect_btn:"మొక్క నాణ్యత తనిఖీ", lbl_inspect_another:"మరొక ఫోటో తనిఖీ",
    lbl_avg_freshness:"సగటు తాజాదనం", lbl_active_batches:"సక్రియ బ్యాచ్‌లు", lbl_wilt_alerts:"వాడిపోవు హెచ్చరికలు",
    lbl_climate_sim:"వాతావరణ సిమ్యులేటర్", lbl_qr_btn:"QR కోడ్ రూపొందించు",
    lbl_your_identity:"మీ గుర్తింపు", lbl_overall_rating_lbl:"మొత్తం రేటింగ్",
    herbs: HERBS.te,
  },

  kn: {
    simpleMode:"ಸರಳ ಮೋಡ್", farmerTab:"🌱 ರೈತ", chefTab:"👨‍🍳 ಅಡುಗೆಯವರು",
    backFull:"← ಪೂರ್ಣ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್", iconMode:"ಚಿಹ್ನೆಗಳು ಮಾತ್ರ", labelMode:"ಲೇಬಲ್‌ಗಳೊಂದಿಗೆ",
    sensors:"ಫಾರ್ಮ್ ಸೆನ್ಸರ್‌ಗಳು", harvest:"ಕೊಯ್ಲು ಸ್ಥಿತಿ", available:"ಇಂದು ಲಭ್ಯ",
    temp:"ತಾಪಮಾನ", humidity:"ತೇವಾಂಶ", air:"ಗಾಳಿ ಗುಣಮಟ್ಟ", light:"ಬೆಳಕು", ph:"pH ಮಟ್ಟ",
    good:"ಉತ್ತಮ ✅", warn:"ಎಚ್ಚರಿಕೆ ⚠️", bad:"ತುರ್ತು 🚨",
    fresh:"ತುಂಬಾ ತಾಜಾ", pickSoon:"2 ದಿನಗಳಲ್ಲಿ ಕೊಯ್ಯಿ", pickNow:"ಈಗಲೇ ಕೊಯ್ಯಿ!",
    daysLeft:"ದಿನಗಳು ಉಳಿದಿವೆ", kgAvail:"ಕಿಲೋ ಲಭ್ಯ", priceKg:"ಕಿಲೋಗೆ",
    orderSoon:"ಶೀಘ್ರ ಆರ್ಡರ್ ಮಾಡಿ", plenty:"ಸ್ಟಾಕ್ ಇದೆ", lowStock:"ಕಡಿಮೆ ಸ್ಟಾಕ್!",
    whatsapp:"📱 WhatsApp ಆರ್ಡರ್", expiresIn:"ಮುಕ್ತಾಯ ಸಮಯ",
    harvestPrediction:"ಉತ್ತಮ ಕೊಯ್ಲು ದಿನ",
    nav_dashboard:"ಡ್ಯಾಶ್‌ಬೋರ್ಡ್", nav_analytics:"ವಿಶ್ಲೇಷಣೆ",
    nav_freshness:"ತಾಜಾತನ ಟ್ರ್ಯಾಕರ್", nav_market:"ಗಿಡಮೂಲಿಕೆ ಮಾರ್ಕೆಟ್",
    nav_waste:"ತ್ಯಾಜ್ಯ ಮುನ್ಸೂಚನೆ", nav_pulse:"ಚೆಫ್ ಕನೆಕ್ಟ್",
    nav_advisor:"AI ಸಲಹೆಗಾರ", nav_simple:"ಸರಳ ಮೋಡ್",
    sec_overview:"ಅವಲೋಕನ", sec_ai:"AI ವೈಶಿಷ್ಟ್ಯಗಳು", sec_engage:"ತೊಡಗಿಸಿಕೊಳ್ಳುವಿಕೆ",
    lbl_refresh:"ರಿಫ್ರೆಶ್", lbl_signout:"ಸೈನ್ ಔಟ್",
    lbl_send_email:"ಇಮೇಲ್ ಕಳುಹಿಸಿ", lbl_submit:"ಸಲ್ಲಿಸಿ",
    lbl_clear_chat:"ಚಾಟ್ ಅಳಿಸಿ", lbl_active_alerts:"ಸಕ್ರಿಯ ಎಚ್ಚರಿಕೆಗಳು",
    lbl_sort_by:"ವಿಂಗಡಿಸಿ:", lbl_alerts:"ಎಚ್ಚರಿಕೆಗಳು",
    lbl_name:"ನಿಮ್ಮ ಹೆಸರು", lbl_email:"ನಿಮ್ಮ ಇಮೇಲ್",
    lbl_rating:"ರೇಟಿಂಗ್", lbl_reviews:"ಚೆಫ್ ವಿಮರ್ಶೆಗಳು",
    lbl_add_herb:"+ ಗಿಡ ಸೇರಿಸಿ", lbl_send_order:"WhatsApp ಮೂಲಕ ಆರ್ಡರ್",
    lbl_place_order:"ಆರ್ಡರ್ ಮಾಡಿ",
    pg_fresh_title:"ತಾಜಾತನ ಟ್ರ್ಯಾಕರ್", pg_fresh_sub:"AI-ಆಧಾರಿತ ಶೆಲ್ಫ್ ಲೈಫ್ ಮುನ್ಸೂಚನೆ",
    pg_market_title:"ಗಿಡಮೂಲಿಕೆ ಮಾರ್ಕೆಟ್", pg_market_sub:"ನೇರ ಗಿಡಮೂಲಿಕೆ ಬೆಲೆಗಳು",
    pg_waste_title:"ತ್ಯಾಜ್ಯ ಮುನ್ಸೂಚನೆ", pg_waste_sub:"ತ್ಯಾಜ್ಯವನ್ನು ಆದಾಯವಾಗಿ ಪರಿವರ್ತಿಸಿ",
    pg_pulse_title:"ಚೆಫ್ ಪಲ್ಸ್", pg_pulse_sub:"ನಿಮ್ಮ ಅನುಭವ ಹಂಚಿಕೊಳ್ಳಿ",
    pg_advisor_title:"AI ಸಲಹೆಗಾರ", pg_advisor_sub:"Groq Llama 70B · ನೇರ ಫಾರ್ಮ್ ಡೇಟಾ",
    lbl_yield:"ಒಟ್ಟು ಇಳುವರಿ", lbl_water:"ನೀರಿನ ಬಳಕೆ", lbl_power:"ವಿದ್ಯುತ್",
    lbl_delivery:"ಸರಾಸರಿ ವಿತರಣೆ", lbl_live_sensors:"ನೇರ ಸೆನ್ಸರ್‌ಗಳು",
    lbl_farm_health:"ಫಾರ್ಮ್ ಆರೋಗ್ಯ ಸ್ಕೋರ್",
    pg_dash_title:"ಫಾರ್ಮ್ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್", pg_dash_sub:"AgriIntel · ನೇರ ಫಾರ್ಮ್ ಮಾಹಿತಿ",
    pg_analytics_sub:"ವಿವರವಾದ ಫಾರ್ಮ್ ಕಾರ್ಯಕ್ಷಮತೆ · ಫಿಲ್ಟರ್‌ಗಳು",
    pg_photo_title:"AI ಫೋಟೋ ತಪಾಸಣೆ", pg_photo_sub:"ಗಿಡ ಫೋಟೋ → AI ಗುಣಮಟ್ಟ ಪರೀಕ್ಷೆ",
    lbl_which_herb:"ಯಾವ ಗಿಡ ತಪಾಸಣೆ ಮಾಡುತ್ತಿದ್ದೀರಿ?", lbl_inspect_btn:"ಗಿಡ ಗುಣಮಟ್ಟ ತಪಾಸಣೆ", lbl_inspect_another:"ಮತ್ತೊಂದು ಫೋಟೋ",
    lbl_avg_freshness:"ಸರಾಸರಿ ತಾಜಾತನ", lbl_active_batches:"ಸಕ್ರಿಯ ಬ್ಯಾಚ್‌ಗಳು", lbl_wilt_alerts:"ಬಾಡುವ ಎಚ್ಚರಿಕೆಗಳು",
    lbl_climate_sim:"ಹವಾಮಾನ ಸಿಮ್ಯುಲೇಟರ್", lbl_qr_btn:"QR ಕೋಡ್ ರಚಿಸಿ",
    lbl_your_identity:"ನಿಮ್ಮ ಗುರುತು", lbl_overall_rating_lbl:"ಒಟ್ಟು ರೇಟಿಂಗ್",
    herbs: HERBS.kn,
  },

  ml: {
    simpleMode:"ലളിത മോഡ്", farmerTab:"🌱 കർഷകൻ", chefTab:"👨‍🍳 പാചകക്കാരൻ",
    backFull:"← പൂർണ്ണ ഡാഷ്‌ബോർഡ്", iconMode:"ഐക്കണുകൾ മാത്രം", labelMode:"ലേബലുകളോടെ",
    sensors:"ഫാം സെൻസറുകൾ", harvest:"വിളവെടുപ്പ് നില", available:"ഇന്ന് ലഭ്യം",
    temp:"താപനില", humidity:"ഈർപ്പം", air:"വായു ഗുണനിലവാരം", light:"വെളിച്ചം", ph:"pH നില",
    good:"നല്ലത് ✅", warn:"ശ്രദ്ധിക്കുക ⚠️", bad:"അടിയന്തിരം 🚨",
    fresh:"വളരെ പുതിയത്", pickSoon:"2 ദിവസത്തിൽ പറിക്കുക", pickNow:"ഇപ്പോൾ പറിക്കുക!",
    daysLeft:"ദിവസം ബാക്കി", kgAvail:"കിലോ ലഭ്യം", priceKg:"കിലോയ്ക്ക്",
    orderSoon:"ഉടൻ ഓർഡർ ചെയ്യുക", plenty:"സ്റ്റോക്ക് ഉണ്ട്", lowStock:"കുറഞ്ഞ സ്റ്റോക്ക്!",
    whatsapp:"📱 WhatsApp ഓർഡർ", expiresIn:"കാലഹരണം",
    harvestPrediction:"മികച്ച വിളവെടുപ്പ് ദിവസം",
    nav_dashboard:"ഡാഷ്‌ബോർഡ്", nav_analytics:"വിശകലനം",
    nav_freshness:"ഫ്രഷ്‌നസ് ട്രാക്കർ", nav_market:"ഔഷധ സസ്യ മാർക്കറ്റ്",
    nav_waste:"മാലിന്യ പ്രവചനം", nav_pulse:"ഷെഫ് കണക്ട്",
    nav_advisor:"AI ഉപദേഷ്ടാവ്", nav_simple:"ലളിത മോഡ്",
    sec_overview:"അവലോകനം", sec_ai:"AI ഫീച്ചറുകൾ", sec_engage:"ഇടപഴകൽ",
    lbl_refresh:"റിഫ്രഷ്", lbl_signout:"സൈൻ ഔട്ട്",
    lbl_send_email:"ഇമെയിൽ അയയ്ക്കുക", lbl_submit:"സമർപ്പിക്കുക",
    lbl_clear_chat:"ചാറ്റ് മായ്ക്കുക", lbl_active_alerts:"സജീവ അലർട്ടുകൾ",
    lbl_sort_by:"ക്രമപ്പെടുത്തുക:", lbl_alerts:"അലർട്ടുകൾ",
    lbl_name:"നിങ്ങളുടെ പേര്", lbl_email:"നിങ്ങളുടെ ഇമെയിൽ",
    lbl_rating:"റേറ്റിംഗ്", lbl_reviews:"ഷെഫ് അവലോകനങ്ങൾ",
    lbl_add_herb:"+ സസ്യം ചേർക്കുക", lbl_send_order:"WhatsApp വഴി ഓർഡർ",
    lbl_place_order:"ഓർഡർ ചെയ്യുക",
    pg_fresh_title:"ഫ്രഷ്‌നസ് ട്രാക്കർ", pg_fresh_sub:"AI-ഉപയോഗിക്കുന്ന ഷെൽഫ് ലൈഫ് പ്രവചനം",
    pg_market_title:"ഔഷധ സസ്യ മാർക്കറ്റ്", pg_market_sub:"നേരിട്ടുള്ള ഔഷധ സസ്യ വിലകൾ",
    pg_waste_title:"മാലിന്യ പ്രവചനം", pg_waste_sub:"മാലിന്യം വരുമാനമാക്കുക",
    pg_pulse_title:"ഷെഫ് പൾസ്", pg_pulse_sub:"നിങ്ങളുടെ അനുഭവം പങ്കിടുക",
    pg_advisor_title:"AI ഉപദേഷ്ടാവ്", pg_advisor_sub:"Groq Llama 70B · നേരിട്ടുള്ള ഫാം ഡേറ്റ",
    lbl_yield:"മൊത്തം വിളവ്", lbl_water:"ജലോപഭോഗം", lbl_power:"വൈദ്യുതി",
    lbl_delivery:"ശരാശരി ഡെലിവറി", lbl_live_sensors:"നേരിട്ടുള്ള സെൻസറുകൾ",
    lbl_farm_health:"ഫാം ആരോഗ്യ സ്കോർ",
    pg_dash_title:"ഫാം ഡാഷ്‌ബോർഡ്", pg_dash_sub:"AgriIntel · നേരിട്ടുള്ള ഫാം ഇന്റലിജൻസ്",
    pg_analytics_sub:"വിശദ ഫാം പ്രകടനം · ഇന്ററാക്ടീവ് ഫിൽട്ടറുകൾ",
    pg_photo_title:"AI ഫോട്ടോ പരിശോധന", pg_photo_sub:"സസ്യ ഫോട്ടോ → AI ഗുണമേന്മ പരിശോധന",
    lbl_which_herb:"ഏത് സസ്യം പരിശോധിക്കുന്നു?", lbl_inspect_btn:"സസ്യ ഗുണനിലവാരം പരിശോധിക്കുക", lbl_inspect_another:"മറ്റൊരു ഫോട്ടോ",
    lbl_avg_freshness:"ശരാശരി ഫ്രഷ്‌നസ്", lbl_active_batches:"സജീവ ബാച്ചുകൾ", lbl_wilt_alerts:"വാട്ടം അലർട്ടുകൾ",
    lbl_climate_sim:"കാലാവസ്ഥ സിമുലേറ്റർ", lbl_qr_btn:"QR കോഡ് ഉണ്ടാക്കുക",
    lbl_your_identity:"നിങ്ങളുടെ ഐഡന്റിറ്റി", lbl_overall_rating_lbl:"മൊത്തത്തിലുള്ള റേറ്റിംഗ്",
    herbs: HERBS.ml,
  },

  bn: {
    simpleMode:"সহজ মোড", farmerTab:"🌱 কৃষক", chefTab:"👨‍🍳 রন্ধনশিল্পী",
    backFull:"← পূর্ণ ড্যাশবোর্ড", iconMode:"শুধু আইকন", labelMode:"লেবেলসহ",
    sensors:"খামার সেন্সর", harvest:"ফসল কাটার অবস্থা", available:"আজ উপলব্ধ",
    temp:"তাপমাত্রা", humidity:"আর্দ্রতা", air:"বায়ু মান", light:"আলো", ph:"pH মাত্রা",
    good:"ভালো ✅", warn:"সতর্কতা ⚠️", bad:"জরুরি 🚨",
    fresh:"খুব তাজা", pickSoon:"২ দিনে তুলুন", pickNow:"এখনই তুলুন!",
    daysLeft:"দিন বাকি", kgAvail:"কেজি উপলব্ধ", priceKg:"প্রতি কেজি",
    orderSoon:"শীঘ্রই অর্ডার করুন", plenty:"পর্যাপ্ত আছে", lowStock:"কম স্টক!",
    whatsapp:"📱 WhatsApp অর্ডার", expiresIn:"মেয়াদ শেষ",
    harvestPrediction:"সেরা ফসল কাটার দিন",
    nav_dashboard:"ড্যাশবোর্ড", nav_analytics:"বিশ্লেষণ",
    nav_freshness:"তাজা ট্র্যাকার", nav_market:"ভেষজ বাজার",
    nav_waste:"অপচয় পূর্বাভাস", nav_pulse:"শেফ কানেক্ট",
    nav_advisor:"AI উপদেষ্টা", nav_simple:"সহজ মোড",
    sec_overview:"সংক্ষিপ্ত", sec_ai:"AI বৈশিষ্ট্য", sec_engage:"সম্পৃক্ততা",
    lbl_refresh:"রিফ্রেশ", lbl_signout:"সাইন আউট",
    lbl_send_email:"ইমেইল পাঠান", lbl_submit:"জমা দিন",
    lbl_clear_chat:"চ্যাট মুছুন", lbl_active_alerts:"সক্রিয় সতর্কতা",
    lbl_sort_by:"সাজান:", lbl_alerts:"সতর্কতা",
    lbl_name:"আপনার নাম", lbl_email:"আপনার ইমেইল",
    lbl_rating:"রেটিং", lbl_reviews:"শেফ পর্যালোচনা",
    lbl_add_herb:"+ ভেষজ যোগ করুন", lbl_send_order:"WhatsApp-এ অর্ডার পাঠান",
    lbl_place_order:"অর্ডার করুন",
    pg_fresh_title:"তাজা ট্র্যাকার", pg_fresh_sub:"AI-চালিত শেলফ লাইফ পূর্বাভাস",
    pg_market_title:"ভেষজ বাজার", pg_market_sub:"সরাসরি ভেষজ মূল্য",
    pg_waste_title:"অপচয় পূর্বাভাস", pg_waste_sub:"অপচয়কে আয়ে পরিণত করুন",
    pg_pulse_title:"শেফ পালস", pg_pulse_sub:"আপনার অভিজ্ঞতা শেয়ার করুন",
    pg_advisor_title:"AI উপদেষ্টা", pg_advisor_sub:"Groq Llama 70B · সরাসরি ফার্ম ডেটা",
    lbl_yield:"মোট ফলন", lbl_water:"জলের ব্যবহার", lbl_power:"বিদ্যুৎ",
    lbl_delivery:"গড় ডেলিভারি", lbl_live_sensors:"সরাসরি সেন্সর",
    lbl_farm_health:"ফার্ম স্বাস্থ্য স্কোর",
    pg_dash_title:"ফার্ম ড্যাশবোর্ড", pg_dash_sub:"AgriIntel · রিয়েল-টাইম ফার্ম তথ্য",
    pg_analytics_sub:"বিস্তারিত ফার্ম কার্যক্ষমতা · ইন্টারেক্টিভ ফিল্টার",
    pg_photo_title:"AI ফটো পরিদর্শন", pg_photo_sub:"ভেষজ ফটো → AI মান পরীক্ষা",
    lbl_which_herb:"আপনি কোন ভেষজ পরিদর্শন করছেন?", lbl_inspect_btn:"ভেষজ গুণমান পরীক্ষা করুন", lbl_inspect_another:"আরেকটি ফটো পরীক্ষা",
    lbl_avg_freshness:"গড় তাজাভাব", lbl_active_batches:"সক্রিয় ব্যাচ", lbl_wilt_alerts:"ঝরে পড়ার সতর্কতা",
    lbl_climate_sim:"জলবায়ু সিমুলেটর", lbl_qr_btn:"QR কোড তৈরি করুন",
    lbl_your_identity:"আপনার পরিচয়", lbl_overall_rating_lbl:"সামগ্রিক রেটিং",
    herbs: HERBS.bn,
  },

  mr: {
    simpleMode:"सोपा मोड", farmerTab:"🌱 शेतकरी", chefTab:"👨‍🍳 आचारी",
    backFull:"← पूर्ण डॅशबोर्ड", iconMode:"फक्त चिन्हे", labelMode:"लेबलसह",
    sensors:"शेत सेन्सर", harvest:"कापणी स्थिती", available:"आज उपलब्ध",
    temp:"तापमान", humidity:"ओलावा", air:"हवा गुणवत्ता", light:"प्रकाश", ph:"pH पातळी",
    good:"चांगले ✅", warn:"लक्ष द्या ⚠️", bad:"तातडीचे 🚨",
    fresh:"अतिशय ताजे", pickSoon:"२ दिवसात काढा", pickNow:"आत्ताच काढा!",
    daysLeft:"दिवस उरले", kgAvail:"किलो उपलब्ध", priceKg:"प्रति किलो",
    orderSoon:"लवकर ऑर्डर करा", plenty:"साठा आहे", lowStock:"कमी साठा!",
    whatsapp:"📱 WhatsApp ऑर्डर", expiresIn:"मुदत संपणार",
    harvestPrediction:"सर्वोत्तम कापणीचा दिवस",
    nav_dashboard:"डॅशबोर्ड", nav_analytics:"विश्लेषण",
    nav_freshness:"ताजेपणा ट्रॅकर", nav_market:"औषधी वनस्पती बाजार",
    nav_waste:"कचरा भविष्यवक्ता", nav_pulse:"शेफ कनेक्ट",
    nav_advisor:"AI सल्लागार", nav_simple:"सोपा मोड",
    sec_overview:"विहंगावलोकन", sec_ai:"AI वैशिष्ट्ये", sec_engage:"सहभाग",
    lbl_refresh:"रिफ्रेश", lbl_signout:"साइन आउट",
    lbl_send_email:"ईमेल पाठवा", lbl_submit:"सबमिट करा",
    lbl_clear_chat:"चॅट साफ करा", lbl_active_alerts:"सक्रिय सूचना",
    lbl_sort_by:"क्रमवारी:", lbl_alerts:"सूचना",
    lbl_name:"तुमचे नाव", lbl_email:"तुमचा ईमेल",
    lbl_rating:"रेटिंग", lbl_reviews:"शेफ समीक्षा",
    lbl_add_herb:"+ औषधी वनस्पती जोडा", lbl_send_order:"WhatsApp द्वारे ऑर्डर",
    lbl_place_order:"ऑर्डर करा",
    pg_fresh_title:"ताजेपणा ट्रॅकर", pg_fresh_sub:"AI-आधारित शेल्फ लाइफ अंदाज",
    pg_market_title:"औषधी वनस्पती बाजार", pg_market_sub:"थेट औषधी वनस्पती किंमती",
    pg_waste_title:"कचरा भविष्यवक्ता", pg_waste_sub:"कचऱ्याचे उत्पन्नात रूपांतर करा",
    pg_pulse_title:"शेफ पल्स", pg_pulse_sub:"तुमचा अनुभव शेअर करा",
    pg_advisor_title:"AI सल्लागार", pg_advisor_sub:"Groq Llama 70B · थेट शेत डेटा",
    lbl_yield:"एकूण उत्पन्न", lbl_water:"पाण्याचा वापर", lbl_power:"वीज",
    lbl_delivery:"सरासरी डिलिव्हरी", lbl_live_sensors:"थेट सेन्सर",
    lbl_farm_health:"शेत आरोग्य गुण",
    pg_dash_title:"फार्म डॅशबोर्ड", pg_dash_sub:"AgriIntel · रिअल-टाइम फार्म माहिती",
    pg_analytics_sub:"तपशीलवार फार्म कामगिरी · इंटरेक्टिव्ह फिल्टर",
    pg_photo_title:"AI फोटो तपासणी", pg_photo_sub:"औषधी वनस्पती फोटो → AI गुणवत्ता तपासणी",
    lbl_which_herb:"कोणती औषधी वनस्पती तपासत आहात?", lbl_inspect_btn:"औषधी वनस्पती गुणवत्ता तपासा", lbl_inspect_another:"दुसरा फोटो तपासा",
    lbl_avg_freshness:"सरासरी ताजेपणा", lbl_active_batches:"सक्रिय तुकडे", lbl_wilt_alerts:"कोमेजण्याच्या सूचना",
    lbl_climate_sim:"हवामान सिम्युलेटर", lbl_qr_btn:"QR कोड तयार करा",
    lbl_your_identity:"तुमची ओळख", lbl_overall_rating_lbl:"एकूण रेटिंग",
    herbs: HERBS.mr,
  },

  gu: {
    simpleMode:"સરળ મોડ", farmerTab:"🌱 ખેડૂત", chefTab:"👨‍🍳 રસોઇઓ",
    backFull:"← સંપૂર્ણ ડેશબોર્ડ", iconMode:"ફક્ત ચિહ્નો", labelMode:"લેબલ સાથે",
    sensors:"ખેત સેન્સર", harvest:"લણણી સ્થિતિ", available:"આજે ઉપલબ્ધ",
    temp:"તાપમાન", humidity:"ભેજ", air:"હવા ગુણવત્તા", light:"પ્રકાશ", ph:"pH સ્તર",
    good:"સારું ✅", warn:"ધ્યાન આપો ⚠️", bad:"તાત્કાલિક 🚨",
    fresh:"ખૂબ તાજું", pickSoon:"૨ દિવસમાં ઉઠાવો", pickNow:"અત્યારે ઉઠાવો!",
    daysLeft:"દિવસ બાકી", kgAvail:"કિલો ઉપલબ્ધ", priceKg:"પ્રતિ કિલો",
    orderSoon:"ઝડપથી ઓર્ડર કરો", plenty:"સ્ટોક છે", lowStock:"ઓછો સ્ટોક!",
    whatsapp:"📱 WhatsApp ઓર્ડર", expiresIn:"સમાપ્ત થવા સુધી",
    harvestPrediction:"શ્રેષ્ઠ લણણી દિવસ",
    nav_dashboard:"ડેશબોર્ડ", nav_analytics:"વિશ્લેષણ",
    nav_freshness:"તાજગી ટ્રેકર", nav_market:"ઔષધ વનસ્પતિ બજાર",
    nav_waste:"કચરો આગાહી", nav_pulse:"શેફ કનેક્ટ",
    nav_advisor:"AI સલાહકાર", nav_simple:"સરળ મોડ",
    sec_overview:"ઝાંખી", sec_ai:"AI વૈશિષ્ટ્ય", sec_engage:"સહભાગiтa",
    lbl_refresh:"રિફ્રેશ", lbl_signout:"સાઇન આઉટ",
    lbl_send_email:"ઇમેઇલ મોકલો", lbl_submit:"સબમિટ",
    lbl_clear_chat:"ચેટ સાફ કરો", lbl_active_alerts:"સક્રિય ચેતવણી",
    lbl_sort_by:"ગોઠવો:", lbl_alerts:"ચેતવણી",
    lbl_name:"તમારું નામ", lbl_email:"તમારો ઇમેઇલ",
    lbl_rating:"રેટિંગ", lbl_reviews:"શેફ સમીક્ષા",
    lbl_add_herb:"+ વનસ્પતિ ઉમેરો", lbl_send_order:"WhatsApp દ્વારા ઓર્ડર",
    lbl_place_order:"ઓર્ડર કરો",
    pg_fresh_title:"તાજગી ટ્રેકર", pg_fresh_sub:"AI-સંચાલિત શેલ્ફ લાઇફ આગાહી",
    pg_market_title:"ઔષધ વનસ્પતિ બજાર", pg_market_sub:"સીધી ઔષધ વનસ્પતિ કિંમતો",
    pg_waste_title:"કચરો આગાહી", pg_waste_sub:"કચરાને આવક માં ફેરવો",
    pg_pulse_title:"શેફ પલ્સ", pg_pulse_sub:"તમારો અનુભવ શેર કરો",
    pg_advisor_title:"AI સલાહકાર", pg_advisor_sub:"Groq Llama 70B · સીધો ફાર્મ ડેટા",
    lbl_yield:"કુલ ઉત્પાદન", lbl_water:"પાણીનો ઉપયોગ", lbl_power:"વીજળી",
    lbl_delivery:"સરેરાશ ડિલિવરી", lbl_live_sensors:"સીધા સેન્સર",
    lbl_farm_health:"ફાર્મ આરોગ્ય સ્કોર",
    pg_dash_title:"ફાર્મ ડેશબોર્ડ", pg_dash_sub:"AgriIntel · રિઅલ-ટાઇમ ફાર્મ ઇન્ટેલિજન્સ",
    pg_analytics_sub:"વિગતવાર ફાર્મ પ્રદર્શન · ઇન્ટરેક્ટિવ ફિલ્ટર",
    pg_photo_title:"AI ફોટો નિરીક્ષણ", pg_photo_sub:"ઔષધ વનસ્પતિ ફોટો → AI ગુણવત્તા ચકાસણી",
    lbl_which_herb:"તમે કઈ ઔષધ વનસ્પતિ તપાસી રહ્યા છો?", lbl_inspect_btn:"ઔષધ વનસ્પતિ ગુણવત્તા તપાસો", lbl_inspect_another:"બીજો ફોટો તપાસો",
    lbl_avg_freshness:"સરેરાશ તાજગી", lbl_active_batches:"સક્રિય બૅચ", lbl_wilt_alerts:"કરમાવાની ચેતવણી",
    lbl_climate_sim:"આબોહવા સિમ્યુલેટર", lbl_qr_btn:"QR કોડ બનાવો",
    lbl_your_identity:"તમારી ઓળખ", lbl_overall_rating_lbl:"એકંદર રેટિંગ",
    herbs: HERBS.gu,
  },
};

const LangContext = createContext({ lang:"en", setLang:()=>{}, t: T.en });

export function LangProvider({ children }) {
  const [lang, setLang] = useState("en");
  return (
    <LangContext.Provider value={{ lang, setLang, t: T[lang] }}>
      {children}
    </LangContext.Provider>
  );
}

export const useLang = () => useContext(LangContext);
